import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const html = readFileSync(new URL("../dashboard.html", import.meta.url), "utf8");
const indexHtml = readFileSync(new URL("../index.html", import.meta.url), "utf8");

assert.match(html, /id="heightInput"/);
assert.match(html, /id="weightInput"/);
assert.match(html, /id="goalInput"/);
assert.doesNotMatch(html, /meals:\s*\[\s*\{\s*name:\s*"希腊酸奶碗"/);
assert.match(html, /今天吃了什么？/);
assert.match(html, /placeholder="例如：早餐两个鸡蛋，一杯牛奶；中午200克米饭和150克鸡胸肉"/);
assert.doesNotMatch(html, /id="mealText"/);
assert.doesNotMatch(html, /id="foodSearchInput"/);
assert.doesNotMatch(html, /id="foodGramsInput"/);
assert.doesNotMatch(html, /id="foodSearchResults"/);
assert.doesNotMatch(html, /id="addSelectedFood"/);
assert.doesNotMatch(html, /补充入口/);
assert.doesNotMatch(html, /选食物并输入克数/);
assert.match(html, /searchFoods\(/);
assert.match(html, /foodEntry\(/);
assert.match(html, /id="aiMealText"/);
assert.match(html, /id="aiParseMeal"/);
assert.match(html, /id="addMealButton"/);
assert.match(html, /id="mealReview"/);
assert.match(html, /meal-review-row/);
assert.match(html, /data-review-grams/);
assert.match(html, /confirmMealReview/);
assert.match(html, /parseAiMeal\(/);
assert.match(html, /startVoiceMealInput\(/);
assert.doesNotMatch(html, /#addMealButton"\)\.onclick = \(\) => \$\("#mealText"\)\.focus/);
assert.doesNotMatch(html, /id="logMeal"/);
assert.match(html, /id="routineList"/);
assert.match(html, /id="setList"/);
assert.match(html, /id="partsPicker"/);
assert.match(html, /id="generateWorkout"/);
assert.match(html, /id="dailyWeightInput"/);
assert.match(html, /id="dailyStepsInput"/);
assert.match(html, /id="dailySleepInput"/);
assert.match(html, /id="dailyMoodInput"/);
assert.match(html, /id="activeDateInput"/);
assert.match(html, /id="saveWeekPlan"/);
assert.match(html, /id="trainingWeekdays"/);
assert.match(html, /class="weekdays-picker"/);
assert.doesNotMatch(html, /<select id="trainingWeekdays"/);
assert.match(html, /querySelectorAll\("#trainingWeekdays input:checked"\)/);
assert.match(html, /id="exercisesPerDayInput"/);
assert.match(html, /id="setsPerExerciseInput"/);
assert.match(html, /configuredExerciseCount\(\)/);
assert.match(html, /maxExercises: state\.planConfig\.exercisesPerDay/);
assert.match(html, /id="weekPlanList"/);
assert.match(html, /loadDay\(/);
assert.match(html, /saveDay\(/);
assert.match(html, /id="settleDay"/);
assert.match(html, /id="dailySummary"/);
assert.match(html, /id="historyList"/);
assert.match(html, /id="historyDetail"/);
assert.match(html, /id="deleteHistoryRecord"/);
assert.match(html, /data-history-date/);
assert.match(html, /dailySummary\(/);
assert.match(html, /data-page="training"/);
assert.match(html, /data-page="food"/);
assert.match(html, /data-page="data"/);
assert.match(html, /renderRoute\(/);
assert.match(html, /bindNavigation\(/);
assert.match(html, /data-route/);
assert.match(html, /fallbackRoute/);
assert.match(html, /id="appError"/);
assert.match(html, /exercise-gif/);
assert.match(html, /max-width: 480px/);
assert.match(html, /overflow-x: hidden/);
assert.match(html, /grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/);
assert.doesNotMatch(html, /grid-template-columns: repeat\(4, minmax\(120px, 1fr\)\)/);
assert.match(html, /date-row/);
assert.match(html, /profile-setup/);
assert.match(html, /single-meal-box/);
assert.match(html, /generateWorkout\(/);
assert.match(html, /data-done/);
assert.match(html, /data-add-set/);
assert.match(html, /data-remove-set/);
assert.match(html, /data-weight/);
assert.match(html, /data-reps/);
assert.match(html, /import .*dashboard-logic\.mjs/);
assert.match(html, /render\(\)/);
assert.match(indexHtml, /location\.replace\("dashboard\.html" \+ location\.hash\)/);
assert.match(indexHtml, /url=dashboard\.html/);

console.log("dashboard page wiring checks passed");
